version: "3.5"

services:

  training:
    build: ./ml-kurkkumopo-training
    image: ml-kurkkumopo-training
    container_name: kurkkumopo-training
    volumes:
      - src:/src/model
      - imgs:/src/imgs

  backend:
    build: ./ml-kurkkumopo-backend
    image: ml-kurkkumopo-backend
    ports:
      - 5000:5000
    container_name: kurkkumopo-backend
    volumes:
      - src:/src/model

  frontend:
    build: ./ml-kurkkumopo-frontend
    image: ml-kurkkumopo-frontend
    ports:
      - 8080:3000
    container_name: kurkkumopo-frontend

volumes:
    src:
    imgs:
