version: "3.5"

services:

  frontend:
    image: node_frontend
    build: ./frontend/
    ports:
      - 8080:5000
    container_name: frontend

  backend:
    image: node_backend
    build: ./backend/
    ports:
      - 8000:8000
    volumes:
      - ./logs.txt:/usr/app/logs.txt
    container_name: backend
    environment:
      - REDIS=redis
      - DB_USERNAME=user
      - DB_PASSWORD=example
      - DB_HOST=db_postgres
    depends_on:
      - redis
      - db

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=example
    container_name: db_postgres
    volumes:
      - ./database:/var/lib/postgresql/data


  redis:
    image: redis
    restart: unless-stopped
    container_name: redis_container
    environment:
      - REDIS=localhost
  nginx:
    image: nginx
    depends_on:
      - frontend
      - backend
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

